import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [data, setData] = useState();

  const apiKey = "jzW3Qvyu32qy8tjdBc9H5JQE6JhVWvJrJffm5LCw"

  //const url = `https://api.nasa.gov/techport/api/projects?api_key=${apiKey}`
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`

  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const data = await res.data;
    console.log(data)
    setData(data)
  }

  useEffect(() => {
    getTechTransferData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          data && data.results.map((tech, index) => {
              return(
                <div key={index}>
                
                {
                  tech && tech.map((t, ind) => {
                    if(ind === 10) {
                      return( 
                        <Image src={t} alt="alt" key={ind} width={100} height={100}/>
                      )
                    }
                  })
                }
                </div>
              )
          })
        }
      </main>
    </>
  )
}
